[build-system]
requires = ["setuptools"]

[project]
name = "timetracker"
version = "0.0.0"
description = "Time Tracking"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "setuptools",
]